const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@Baaba Devs";
const searchanything = "Search anything...",
    todayDeal = "Today's Deal",
    flashsale = "Flash Sale",
    topSellers = "Top Sellers",
    brand = "Brand",
    topCategories = "Top Categories",
    womenDress = "Women Dress",
    girlsWatches = "Girls Watches",
    mobilePhone = "Mobile Phone",
    boysGlasses = "Boys Glasses",
    tShirts = "T-Shirts",
    girlsDress = "Girls Dresses",
    featuredProduct = "Featured Product",
    featuredCategories = "Featured Categories";
const womenClothing = "Women Clothing",
    menClothingFashion = "Men Clothing & Fashion",
    compAccess = "Computer & Accessories",
    automobile = "Automobile",
    Kidtoys = "Kids & Toys",
    sports = "Sports",
    jewelry = "Jewelry",
    cellphone = "Cellphone & Tab",
    furniture = "Furniture";
